title: Angela C. Jin
url: "https://angelacjin.github.io"
description: "Angela Jin Berkeley EECS"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resources"
   link: "/resources"
 - name: "Contact"
   link: "contact"
